package com.lynn.reverbtime.RoomComponent;

import javax.persistence.*;

/*
Class modeling a room component eg. a wall made out of concrete or wood etc. Every component has a unique name and
an absorption coefficient used for computing reverberation time in the room. The ID ist auto generated by the database.
*/

@Entity
@Table
public class RoomComponent {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Column(unique=true)
    private String name;
    private Double alpha;

    public RoomComponent() {
    }

    public RoomComponent(Long id, String name, Double alpha) {
        this.id = id;
        this.name = name;
        this.alpha = alpha;
    }

    public RoomComponent(String name, Double alpha) {
        this.name = name;
        this.alpha = alpha;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getAlpha() {
        return alpha;
    }

    public void setAlpha(Double alpha) {
        this.alpha = alpha;
    }

    @Override
    public String toString() {
        return "RoomComponent{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", alpha=" + alpha +
                '}';
    }
}
